<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_I Agree__25r3t_lrPF3M6zD2YkWvZU</name>
   <tag></tag>
   <elementGuidId>9e3e0ddf-82f2-4fa4-8d23-ac3a158e3dd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe._25r3t_lrPF3M6zD2YkWvZU</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SHORTCUT_FOCUSABLE_DIV']/div[3]/div[3]/div/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.reddit.com/login/?experiment_d2x_2020ify_buttons=enabled&amp;experiment_d2x_sso_login_link=enabled</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_25r3t_lrPF3M6zD2YkWvZU</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SHORTCUT_FOCUSABLE_DIV&quot;)/div[3]/div[@class=&quot;_1UtFUrE2ijAe5ba5uPgcfQ&quot;]/div[@class=&quot;_34uo64r1j-TcpBGXAQcZJ1&quot;]/iframe[@class=&quot;_25r3t_lrPF3M6zD2YkWvZU&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SHORTCUT_FOCUSABLE_DIV']/div[3]/div[3]/div/iframe</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
   </webElementXpaths>
</WebElementEntity>
